[package]
name = "mem"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config  = { path = "../../domain-lib/config" }
arch = { path = "../../domain-lib/arch" }
ksync = { path = "../../domain-lib/ksync" }
platform = { path = "../platform" }
page_table = { path = "./crates/page-table", package = "page-table" }
memory_addr = { path = "./crates/memory_addr" }
ptable = { path = "./crates/vmspace", package = "vmspace" }
pconst = { path = "../../utils/pconst", features = ["special_error"] }
talc = { version = "4" }
pager = { path = "./crates/pager", default-features = false, optional = true }
spin = "0"
log = "0"
heapless = "0.8"

[features]
default = ["pager_bitmap",]
pager_buddy = ["pager/buddy"]
pager_bitmap = ["pager/bitmap"]
memory_test = []