[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mem = { path = "../base/mem" }
platform = { path = "../base/platform" }
log = "0"
xmas-elf = "0.10"
pconst = { path = "../utils/pconst", features = [
    "special_error",
] }
spin = "0"

ksync = { path = "../domain-lib/ksync" }
arch = { path = "../domain-lib/arch" }
config = { path = "../domain-lib/config" }
shared_heap = { path = "../domain-lib/shared_heap" }
interface = { path = "../domain-lib/interface" }
corelib = { path = "../domain-lib/corelib" }
basic = { path = "../domain-lib/basic", features = ["task"] }
task_meta = { path = "../domain-lib/task_meta" }
storage = { path = "../domain-lib/storage" }
loader = { path = "../domain-lib/loader" }
domain_manager = { path = "../domain-lib/domain_manager" }

vfscore = { path = "../rvfs-ref/vfscore-ref", package = "vfscore-ref", features = [
    "linux_error",
] }
cpio_reader = { workspace = true }
libflate = { workspace = true }
core2 = { version = "0.4", default-features = false }
fdt = "0.1.5"
hashbrown = "0.14.5"
unwinding = { version="0.2.8", default-features = false, features = [
    "unwinder",
    "fde-gnu-eh-frame-hdr",
    "panic",
    "personality",
], optional = true }
percpu = "0.3"

# Architecture-specific dependencies
[target.'cfg(target_arch = "riscv64")'.dependencies]
riscv = "0.11"


[target.'cfg(target_arch = "x86_64")'.dependencies]
x86 = "0.52.0"
x86_64 = "0.14.0"
acpi = "6.1.0"
aml = "0.16.4"
acpi-resource-parser = { path = "../utils/acpi-resource-parser" }
x86-pci = { path = "../utils/x86-pci" }


[features]
default = ["rust-unwind", "time-tick"]
rust-unwind = ["dep:unwinding"]
bench = []
apic_timer_test = ["platform/apic_timer_test"]
unwind_test = []
time-tick = []
memory_test = ["mem/memory_test"]
trap_test = []
domain_test = [
    "domain_syscall_test",
    "domain_task_test",
    "domain_apic_test",
    "domain_uart_test",
    "domain_block_test",
    "domain_net_test",
]
domain_syscall_test = []
domain_task_test = []
domain_apic_test = []
domain_uart_test = []
domain_block_test = []
domain_net_test = []
strict_locator = []


[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(plat_vf2)',
    'cfg(plat_qemu_riscv)',
    'cfg(plat_qemu_x86_64)',
    'cfg(plat_vf2_sd)',
] }
